title: Kern's Dev Notes
email: kern.handa@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Random notes from a random developer. Likely to be focused around C++ and Python.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://kernhanda.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  kernhanda
name: "Kern Handa"
repository: "kernhanda/kernhanda.github.io"
author:
    name: "Kern Handa"
    avatar: https://avatars0.githubusercontent.com/u/1303719
    bio: I’m a developer at Microsoft Research, working on <u><a href="https://github.com/microsoft/ell">ELL</a></u>.
    location: WA, USA
    linkedin: kernhanda
    github: kernhanda

comments:
    provider: "staticman_v2"
staticman:
    branch: "master"

# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: "America/Los_Angeles"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
    input: GFM
    hard_wrap: false
    auto_ids: true
    footnote_nr: 1
    entity_output: as_char
    toc_levels: 1..6
    smart_quotes: lsquo,rsquo,ldquo,rdquo
    enable_coderay: false

# Sass/SCSS
sass:
    sass_dir: _sass
    style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# theme: minimal-mistakes-jekyll
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "contrast"

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-remote-theme
  # - jekyll-data

whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-remote-theme
  # - jekyll-data

defaults:
  - scope:
      path: ""
      type: posts
    values:
        layout: single
        author_profile: true
        read_time: true
        share: true
        comments: true

compress_html:
    clippings: all
    ignore:
        envs: development

# Archives
#  Type
#  - GitHub Pages compatible archive pages built with Liquid ~> type: liquid (default)
#  - Jekyll Archives plugin archive pages ~> type: jekyll-archives
#  Path (examples)
#  - Archive page should exist at path when using Liquid method or you can
#    expect broken links (especially with breadcrumbs enabled)
#  - <base_path>/tags/my-awesome-tag/index.html ~> path: /tags/
#  - <base_path/categories/my-awesome-category/index.html ~> path: /categories/
#  - <base_path/my-awesome-category/index.html ~> path: /
category_archive:
    type: liquid
    path: /categories/
tag_archive:
    type: liquid
    path: /tags/
# https://github.com/jekyll/jekyll-archives
# jekyll-archives:
#   enabled:
#     - categories
#     - tags
#   layouts:
#     category: archive-taxonomy
#     tag: archive-taxonomy
#   permalinks:
#     category: /categories/:name/
#     tag: /tags/:name/

encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

